[package]
name = "oxide-proxy"
version = "0.1.0"
authors = ["Alex Iadicicco <alex@ajitek.net>"]

[dependencies]
badlog = "0.2.5"
bytes = "0.4"
futures = "0.1"
log = "0.3"
tokio-core = "0.1"
tokio-io = "0.1"
